import type { BrandEditorialRules } from "./types";

/**
 * Single source of truth for Planet Sport brand editorial rules.
 * Add a new entry here to extend — no changes required in form components.
 */
export const BRAND_EDITORIAL_RULES: readonly BrandEditorialRules[] = [
  {
    id: "planetf1",
    displayName: "PlanetF1",
    aliases: ["planetf1", "planet f1", "planet-f1", "pf1"],
    defaultLogoUrl: "/brands/planetf1/logo.svg",
    defaultCta: "Read the full story on PlanetF1",
    defaultSignOff: "— PlanetF1",
    hashtagBank: ["#F1", "#Formula1", "#PlanetF1"],
    bannedPhrases: ["guaranteed win", "click here now", "you won't believe"],
    preferredTone: "Authoritative, race-focused, avoid sensationalism.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: {
      x: 280,
      instagram: 2200,
      facebook: 63206,
      linkedin: 3000,
      tiktok: 2200,
    },
    linkHandling: "strip_utm",
    imageOverlayStyle: "lower_third",
    outroDefaults: ["More F1 news at planetf1.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook", "instagram"],
  },
  {
    id: "football365",
    displayName: "Football365",
    aliases: ["football365", "football 365", "f365"],
    defaultLogoUrl: "/brands/football365/logo.svg",
    defaultCta: "Read more on Football365",
    defaultSignOff: "— Football365",
    hashtagBank: ["#Football365", "#PremierLeague", "#UCL"],
    bannedPhrases: ["super league confirmed", "medical done"],
    preferredTone: "Direct, fan-aware, UK football vernacular.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["Latest at football365.com"],
    defaultContentType: "article_promo",
    defaultPlatforms: ["x", "facebook", "instagram"],
  },
  {
    id: "teamtalk",
    displayName: "TEAMtalk",
    aliases: ["teamtalk", "team talk", "tt"],
    defaultLogoUrl: "/brands/teamtalk/logo.svg",
    defaultCta: "Full story on TEAMtalk",
    defaultSignOff: "— TEAMtalk",
    hashtagBank: ["#TEAMtalk", "#PL", "#EFL"],
    bannedPhrases: ["exclusive: done deal"],
    preferredTone: "Punchy tabloid-adjacent but factual; avoid unverified claims.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "corner_bug",
    outroDefaults: ["teamtalk.com"],
    defaultContentType: "article_promo",
    defaultPlatforms: ["x", "facebook"],
  },
  {
    id: "planet_rugby",
    displayName: "Planet Rugby",
    aliases: ["planet rugby", "planetrugby", "planet_rugby", "pr"],
    defaultLogoUrl: "/brands/planet-rugby/logo.svg",
    defaultCta: "Read on Planet Rugby",
    defaultSignOff: "— Planet Rugby",
    hashtagBank: ["#Rugby", "#SixNations", "#PlanetRugby"],
    bannedPhrases: [],
    preferredTone: "Passionate but measured; respect for players and officials.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "lower_third",
    outroDefaults: ["planetrugby.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook", "instagram"],
  },
  {
    id: "love_rugby_league",
    displayName: "Love Rugby League",
    aliases: ["love rugby league", "loverugbyleague", "lrl", "love_rugby_league"],
    defaultLogoUrl: "/brands/love-rugby-league/logo.svg",
    defaultCta: "More on Love Rugby League",
    defaultSignOff: "— Love Rugby League",
    hashtagBank: ["#RugbyLeague", "#SuperLeague", "#NRL"],
    bannedPhrases: [],
    preferredTone: "Community-first, northern hemisphere + NRL aware.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["loverugbyleague.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook"],
  },
  {
    id: "tennis365",
    displayName: "Tennis365",
    aliases: ["tennis365", "tennis 365", "t365"],
    defaultLogoUrl: "/brands/tennis365/logo.svg",
    defaultCta: "Full coverage on Tennis365",
    defaultSignOff: "— Tennis365",
    hashtagBank: ["#Tennis365", "#ATP", "#WTA"],
    bannedPhrases: [],
    preferredTone: "Court-side clarity; respect rankings and injury news.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "lower_third",
    outroDefaults: ["tennis365.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "instagram", "facebook"],
  },
  {
    id: "cricket365",
    displayName: "Cricket365",
    aliases: ["cricket365", "cricket 365", "c365"],
    defaultLogoUrl: "/brands/cricket365/logo.svg",
    defaultCta: "Read more on Cricket365",
    defaultSignOff: "— Cricket365",
    hashtagBank: ["#Cricket365", "#TestCricket", "#IPL"],
    bannedPhrases: [],
    preferredTone: "Stats-friendly, international calendar aware.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["cricket365.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook"],
  },
  {
    id: "golf365",
    displayName: "Golf365",
    aliases: ["golf365", "golf 365", "g365"],
    defaultLogoUrl: "/brands/golf365/logo.svg",
    defaultCta: "Follow on Golf365",
    defaultSignOff: "— Golf365",
    hashtagBank: ["#Golf365", "#PGA", "#DPWorldTour"],
    bannedPhrases: [],
    preferredTone: "Calm, tour-focused; avoid clickbait on majors.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "lower_third",
    outroDefaults: ["golf365.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "instagram"],
  },
  {
    id: "planet_football",
    displayName: "Planet Football",
    aliases: ["planet football", "planetfootball", "planet_football", "pf"],
    defaultLogoUrl: "/brands/planet-football/logo.svg",
    defaultCta: "Read on Planet Football",
    defaultSignOff: "— Planet Football",
    hashtagBank: ["#PlanetFootball", "#SerieA", "#LaLiga"],
    bannedPhrases: [],
    preferredTone: "European leagues balance; multi-language awareness in copy.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["planetfootball.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook", "instagram"],
  },
  {
    id: "sport365",
    displayName: "Sport365",
    aliases: ["sport365", "sport 365", "s365"],
    defaultLogoUrl: "/brands/sport365/logo.svg",
    defaultCta: "More at Sport365",
    defaultSignOff: "— Sport365",
    hashtagBank: ["#Sport365", "#SportsNews"],
    bannedPhrases: [],
    preferredTone: "General sports desk: clear, inclusive, non-partisan.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "corner_bug",
    outroDefaults: ["sport365.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook"],
  },
  {
    id: "planetsport",
    displayName: "Planet Sport",
    aliases: ["planet sport", "planetsport", "planet_sport", "planet sport network"],
    defaultLogoUrl: "/brands/planet-sport/logo.svg",
    defaultCta: "See the full article",
    defaultSignOff: "— Planet Sport",
    hashtagBank: ["#PlanetSport"],
    bannedPhrases: [],
    preferredTone: "Clear, inclusive sports newsroom voice.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200, facebook: 63206 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["planetsport.com"],
    defaultContentType: "article_promo",
    defaultPlatforms: ["facebook", "instagram", "x"],
  },
  {
    id: "racing365",
    displayName: "Racing365",
    aliases: ["racing365", "racing 365", "r365"],
    defaultLogoUrl: "/brands/racing365/logo.svg",
    defaultCta: "Full story on Racing365",
    defaultSignOff: "— Racing365",
    hashtagBank: ["#Racing365", "#F1", "#Motorsport"],
    bannedPhrases: [],
    preferredTone: "Pit-lane precision; safety and regulations respected.",
    emojiGuidance: "sparing",
    maxCaptionLengthByPlatform: { x: 280, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "lower_third",
    outroDefaults: ["racing365.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "instagram", "facebook"],
  },
  {
    id: "grassroot_goals",
    displayName: "Grassroot Goals",
    aliases: ["grassroot goals", "grassrootgoals", "grassroot_goals", "grassroot goals.com"],
    defaultLogoUrl: "/brands/grassroot-goals/logo.svg",
    defaultCta: "More grassroots football at GrassrootGoals.com",
    defaultSignOff: "— Grassroot Goals",
    hashtagBank: ["#Grassroots", "#GrassrootGoals", "#LocalFootball"],
    bannedPhrases: [],
    preferredTone: "Community-first grassroots football — local clubs, volunteers, and pitch-side stories.",
    emojiGuidance: "allowed",
    maxCaptionLengthByPlatform: { x: 280, facebook: 5000, instagram: 2200 },
    linkHandling: "strip_utm",
    imageOverlayStyle: "brand_bug",
    outroDefaults: ["grassrootgoals.com"],
    defaultContentType: "link_post",
    defaultPlatforms: ["x", "facebook", "instagram"],
  },
];
