import type {
  LanguageCode,
  LanguageComplianceNote,
  LanguageGuardrail,
  LanguageMarketRule,
  LanguageProtectedTerm,
  LanguageProviderMode,
  LanguageSportRule,
} from "@/app/lib/language-studio/types";

const now = "2026-01-01T00:00:00.000Z";

export const DEFAULT_GUARDRAILS: LanguageGuardrail[] = [
  ["fact-safety", "Do not invent facts", "Do not invent facts, quotes, outcomes, standings, dates, times, locations, teams or drivers.", "red"],
  ["fact-safety", "Preserve numbers and results", "Do not change numbers, race results, standings, dates, times or locations.", "red"],
  ["translation-safety", "Natural translation", "Translate naturally while preserving source meaning and proper nouns unless glossary says otherwise.", "amber"],
  ["translation-safety", "Quote accuracy", "Translate direct quotes accurately, but do not rewrite or improve them.", "red"],
  ["editorial-safety", "PlanetF1 tone", "Keep PlanetF1 tone: fast, sharp, expert and fan-first without unsupported opinion.", "amber"],
  ["editorial-safety", "No sensationalism", "Do not make content more sensational, softer or more extreme than the source.", "amber"],
  ["seo-safety", "SEO from source facts", "Create SEO title, meta description and slug only from source facts; do not keyword stuff.", "amber"],
  ["compliance-safety", "Compliance flags", "Flag betting, medical, legal, defamatory, likeness or AI disclosure risks.", "red"],
  ["rights-safety", "Media rights", "Do not assume image, video, voice or likeness rights; flag third-party media.", "red"],
].map(([category, title, rule, severity], index) => ({
  id: `seed-guardrail-${index + 1}`,
  category: category as LanguageGuardrail["category"],
  title,
  rule,
  severity: severity as LanguageGuardrail["severity"],
  active: true,
  createdAt: now,
  updatedAt: now,
}));

const protectedTerms = [
  "Formula 1",
  "F1",
  "FIA",
  "DRS",
  "Grand Prix",
  "Sprint",
  "Safety Car",
  "Virtual Safety Car",
  "pit lane",
  "pole position",
  "paddock",
  "constructors' championship",
  "drivers' championship",
  "Max Verstappen",
  "Lewis Hamilton",
  "Charles Leclerc",
  "Lando Norris",
  "George Russell",
  "Fernando Alonso",
  "Oscar Piastri",
  "Carlos Sainz",
  "Sergio Perez",
  "Red Bull",
  "Ferrari",
  "Mercedes",
  "McLaren",
  "Aston Martin",
  "Williams",
  "Alpine",
  "Haas",
  "Racing Bulls",
  "Sauber",
];

export const DEFAULT_PROTECTED_TERMS: LanguageProtectedTerm[] = protectedTerms.map((term, index) => ({
  id: `seed-protected-${index + 1}`,
  term,
  type: /Verstappen|Hamilton|Leclerc|Norris|Russell|Alonso|Piastri|Sainz|Perez/.test(term)
    ? "driver"
    : /Red Bull|Ferrari|Mercedes|McLaren|Aston Martin|Williams|Alpine|Haas|Racing Bulls|Sauber/.test(term)
      ? "team"
      : "technical term",
  doNotTranslate: true,
  approvedVariants: [term],
  notes: "PlanetF1 seed protected term.",
  createdAt: now,
  updatedAt: now,
}));

const languageDefaults: Array<[LanguageCode, string, "ltr" | "rtl", string, LanguageProviderMode]> = [
  ["es", "es-ES", "ltr", "Spain; allow Latin America market override.", "deepl-openai"],
  ["it", "it-IT", "ltr", "Italian F1 editorial tone; natural headlines.", "deepl-openai"],
  ["de", "de-DE", "ltr", "German compound nouns allowed; avoid tabloid phrasing.", "deepl-openai"],
  ["fr", "fr-FR", "ltr", "French motorsport style; preserve quotes accurately.", "deepl-openai"],
  ["nl", "nl-NL", "ltr", "Dutch direct style; keep F1 terms consistent.", "deepl-openai"],
  ["pt", "pt-PT", "ltr", "Portugal by default; allow Brazil market override.", "deepl-openai"],
  ["ar", "ar", "rtl", "RTL support required; store clean text only with language metadata.", "openai"],
  ["zh", "zh-Hans", "ltr", "Use Simplified Chinese by default.", "openai"],
  ["ja", "ja-JP", "ltr", "Japanese natural readability; preserve names and teams.", "openai"],
  ["da", "da-DK", "ltr", "Danish concise headline style.", "deepl-openai"],
  ["fi", "fi-FI", "ltr", "Finnish natural grammar; avoid over-literal phrasing.", "deepl-openai"],
  ["af", "af-ZA", "ltr", "Afrikaans clear editorial style.", "openai"],
  ["zu", "zu-ZA", "ltr", "Zulu clear journalistic style.", "openai"],
  ["xh", "xh-ZA", "ltr", "Xhosa clear journalistic style.", "openai"],
];

export const DEFAULT_MARKET_RULES: LanguageMarketRule[] = languageDefaults.map(([language, locale, direction, notes, fallbackProvider]) => ({
  id: `seed-market-${language}`,
  market: language === "es" ? "Spain" : language === "pt" ? "Portugal" : locale,
  language,
  locale,
  direction,
  seoKeywordRules: "Use source-supported keywords only. Do not keyword stuff.",
  toneRules: "Fast, sharp, expert, fan-first. Do not overhype.",
  spellingRules: notes,
  headlineStyleNotes: "Punchy but factual. Preserve quote meaning.",
  seoNotes: "Keep SEO title under 60 chars where practical and meta description under 160 chars.",
  dateFormat: "locale",
  timeFormat: "locale",
  currencyFormat: "locale",
  complianceNotes: notes,
  fallbackProvider,
  createdAt: now,
  updatedAt: now,
}));

export const DEFAULT_SPORT_RULES: LanguageSportRule[] = [
  {
    id: "seed-sport-f1",
    sport: "Formula 1",
    keyTerms: ["DRS", "Grand Prix", "Sprint", "Safety Car", "Virtual Safety Car", "pit lane", "pole position", "paddock", "stewards", "parc ferme", "constructors' championship", "drivers' championship"],
    dataRules: "Preserve session names, lap times, tyre compounds, penalties, grid positions, race classifications, sprint formats, championship points and steward decisions exactly. Never turn practice pace into confirmed race pace or speculation into fact.",
    protectedStats: ["race result", "qualifying result", "sprint result", "points", "standings", "lap time", "grid position", "penalty", "tyre compound"],
    namingConventions: "Use official driver/team names. Do not translate F1, FIA, DRS, Grand Prix, Sprint or Safety Car unless market rules explicitly allow it.",
    examples: "Max Verstappen, Lando Norris, Red Bull, McLaren, constructors' championship, five-second penalty, P1, Q3.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-horse-racing",
    sport: "Horse Racing",
    keyTerms: ["racecard", "declarations", "runners", "non-runner", "going", "jockey", "trainer", "handicap", "odds", "each-way", "SP", "Cheltenham", "Royal Ascot"],
    dataRules: "Preserve race names, off times, courses, horse names, jockeys, trainers, stalls, weights, going, odds, tips, declarations, non-runners and results exactly. Never invent selections, prices, ground changes, withdrawals or outcomes.",
    protectedStats: ["race time", "course", "horse name", "jockey", "trainer", "odds", "weight", "draw", "result", "going", "non-runner"],
    namingConventions: "Keep racecourse, race title and horse names exactly as supplied. Use UK/Irish racing terminology naturally and avoid US racing terms unless sourced.",
    examples: "Cheltenham, Aintree, Royal Ascot, novice chase, handicap hurdle, each-way, SP, going: soft.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-football",
    sport: "Football",
    keyTerms: ["Premier League", "EFL", "promotion", "relegation", "play-offs", "Champions League", "Europa League", "Conference League", "FA Cup", "League Cup", "World Cup", "VAR", "transfer", "line-up"],
    dataRules: "Preserve clubs, players, scores, fixtures, tables, points, goal difference, tie formats, aggregate scores, penalties, injuries, fees, contracts and transfer status exactly. Never upgrade rumours into confirmed deals. Promotion/relegation/play-off claims must match the sourced table and competition rules. Cup and European references must preserve round, leg, aggregate score, venue and qualification route.",
    protectedStats: ["score", "aggregate score", "penalty score", "fixture date", "table position", "points", "goal difference", "transfer fee", "contract length", "injury timeline", "competition"],
    namingConventions: "Use official club/player names and competition names. Keep FA Cup, League Cup, Champions League, Europa League, Conference League and World Cup recognisable across markets.",
    examples: "Premier League, Championship play-offs, promotion race, relegation battle, FA Cup fifth round, League Cup semi-final, Champions League last 16, Europa League group stage, FIFA World Cup qualifier.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-rugby-union",
    sport: "Rugby Union",
    keyTerms: ["try", "conversion", "penalty", "drop goal", "scrum", "lineout", "ruck", "maul", "sin-bin", "red card", "Six Nations", "Rugby World Cup", "Champions Cup"],
    dataRules: "Preserve final scores, try scorers, cards, kick counts, bonus points, pool standings, injuries and disciplinary outcomes exactly. Do not confuse rugby union with rugby league scoring or terminology.",
    protectedStats: ["score", "try scorer", "conversion", "penalty", "card", "bonus point", "pool points", "fixture date"],
    namingConventions: "Use Rugby Union competition names and positions accurately: prop, hooker, lock, flanker, number eight, scrum-half, fly-half, centre, wing, full-back.",
    examples: "Six Nations, British and Irish Lions, Rugby World Cup, Heineken Champions Cup, bonus-point win, sin-bin.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-rugby-league",
    sport: "Rugby League",
    keyTerms: ["try", "conversion", "goal", "drop goal", "set restart", "six-again", "scrum", "interchange", "Super League", "Challenge Cup", "NRL"],
    dataRules: "Preserve scores, try scorers, goals, cards, bans, injuries, league table positions and play-off implications exactly. Do not use rugby union rules such as lineouts, rucks or mauls unless quoted from a source for context.",
    protectedStats: ["score", "try scorer", "goals", "drop goal", "league points", "ban length", "fixture date", "play-off position"],
    namingConventions: "Use Rugby League competition names and terms accurately: Super League, Challenge Cup, NRL, set restart, six-again, loose forward.",
    examples: "Super League, Challenge Cup final, Magic Weekend, set restart, six-again, golden point.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-cricket",
    sport: "Cricket",
    keyTerms: ["Test", "ODI", "T20", "innings", "wicket", "run rate", "strike rate", "Duckworth-Lewis-Stern", "DLS", "World Cup", "Ashes", "County Championship"],
    dataRules: "Preserve scores, wickets, overs, balls, innings order, batting/bowling figures, run rates, targets, DLS adjustments and series standings exactly. Do not mix Test, ODI and T20 formats.",
    protectedStats: ["score", "wickets", "overs", "balls", "target", "run rate", "strike rate", "bowling figures", "series score", "DLS target"],
    namingConventions: "Use standard cricket score notation and format labels. Keep DLS, lbw, not out and innings terms consistent.",
    examples: "England 276-7, won by five wickets, 3-45, 74 not out, DLS method, The Ashes, Cricket World Cup.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-golf",
    sport: "Golf",
    keyTerms: ["major", "Masters", "PGA Championship", "US Open", "The Open", "Ryder Cup", "birdie", "bogey", "eagle", "par", "cut", "leaderboard"],
    dataRules: "Preserve scores relative to par, round scores, leaderboard positions, tee times, world rankings, cut lines and play-off details exactly. Do not imply a tournament is complete before the sourced round/result says so.",
    protectedStats: ["score to par", "round score", "leaderboard position", "tee time", "cut line", "world ranking", "play-off result"],
    namingConventions: "Use official tournament names and player names. Write The Open, not British Open, unless quoting or market rules require context.",
    examples: "The Masters, The Open, Ryder Cup, five-under 67, missed cut, birdie at the 18th.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-sport-tennis",
    sport: "Tennis",
    keyTerms: ["Grand Slam", "ATP", "WTA", "Davis Cup", "Billie Jean King Cup", "set", "tie-break", "break point", "seed", "ranking", "retired"],
    dataRules: "Preserve match scores, set order, tie-break scores, seeds, rankings, retirements, walkovers, surfaces and tournament rounds exactly. Do not declare a player through unless the source confirms the result.",
    protectedStats: ["match score", "set score", "tie-break score", "seed", "ranking", "round", "surface", "retirement"],
    namingConventions: "Use official player names, tours and tournament names. Keep ATP, WTA, Grand Slam, Wimbledon and Roland-Garros terminology consistent.",
    examples: "Wimbledon, Australian Open, Roland-Garros, US Open, 6-4 3-6 7-6(5), No 1 seed, match point.",
    createdAt: now,
    updatedAt: now,
  },
];

export const DEFAULT_COMPLIANCE_NOTES: LanguageComplianceNote[] = [
  {
    id: "seed-compliance-global-risk",
    market: "Global",
    riskType: "editorial-risk",
    rule: "Flag betting references, medical claims, injury claims, legal claims, defamatory language, media rights and likeness concerns.",
    action: "Escalate red flags before approval.",
    escalationRequired: true,
    createdAt: now,
    updatedAt: now,
  },
];
